namespace Monero.Client.Enums
{
    internal enum MoneroResponseSubType
    {
        // Daemon
        Block,
        BlockCount,
        BlockHeaderByHash,
        BlockHeaderByHeight,
        BlockHeaderByRange,
        BlockHeaderByRecency, // Last Block Header.
        AllConnections,
        NodeInformation,
        HardforkInformation,
        BanInformation,
        FlushTransactionPool,
        OutputHistogram,
        CoinbaseTransactionSum,
        DaemonVersion,
        FeeEstimate,
        AlternateChain,
        RelayTransaction,
        SyncInformation,
        SetBans,
        SubmitBlock,
        GetBlockTemplate,
        GetBanStatus, // Status on the ban of an address.
        PruneBlockchain,
        TransactionPoolBacklog,
        Transactions,
        TransactionPoolTransactions,

        // Wallet
        Balance,
        Address,
        AddressIndex,
        AddressCreation,
        AddressLabeling,
        Account,
        AccountCreation,
        AccountLabeling,
        AccountTags,
        AccountTagging,
        AccountUntagging,
        AccountTagAndDescriptionSetting,
        Height,
        FundTransfer,
        FundTransferSplit,
        SignTransfer,   // Cold-signing process.
        SubmitTransfer, // Cold-signing process.
        SweepDust,
        SweepAll,
        SaveWallet,
        StopWallet,
        IncomingTransfers,
        QueryPrivateKey,
        SetTransactionNotes,
        GetTransactionNotes,
        GetTransactionKey,
        CheckTransactionKey,
        Transfers,
        TransferByTxid,
        Sign,
        Verify,
        ImportOutputs,
        ExportOutputs,
        ImportKeyImages,
        ExportKeyImages,
        MakeUri,
        ParseUri,
        GetAddressBook,
        AddAddressBook,
        DeleteAddressBook,
        Refresh,
        RescanSpent,
        Languages,
        CreateWallet,
        OpenWallet,
        CloseWallet,
        ChangeWalletPassword,
        RpcVersion,
        IsMultiSig,
        PrepareMultiSig,
        MakeMultiSig,
        ExportMultiSigInfo,
        ImportMultiSigInfo,
        FinalizeMultiSig,
        SignMultiSigTransaction,
        SubmitMultiSigTransaction,
        DescribeTransfer,
        SweepSingle,
        GetPaymentDetail,
        GetAttribute,
        SetAttribute,
        ValidateAddress,
    }
}
